# typed: false
# frozen_string_literal: true
#
# Homebrew formula for wut (source build from this repo).
#
# The canonical tap formula is generated by goreleaser on release and lives at
# github.com/sonyabytes/homebrew-tap. This file exists so users (and you, during
# development) can `brew install --build-from-source ./Formula/wut.rb`
# against a working tree without waiting for a release.
#
# Version / url / sha256 are intentionally generic — the tap formula is the
# authoritative release artifact.

class Wut < Formula
  desc "Route accidental natural-language shell input to your AI harness"
  homepage "https://github.com/sonyabytes/wut"
  license "MIT"

  head "https://github.com/sonyabytes/wut.git", branch: "main"

  depends_on "go" => :build

  def install
    ldflags = "-s -w -X main.Version=#{version}"
    system "go", "build", "-ldflags", ldflags, "-o", bin/"wut", "./cmd/wut"
  end

  def caveats
    <<~EOS
      Finish setup (picks harness, writes config, wires the shell hook):
        wut setup
        wut doctor          # sanity-check the config
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wut version")
  end
end
